name: 'black-list'
replicaCount: 1

images:
  PullSecrets:
    name: kartoffelreg
  repository: genesisproject.azurecr.io/black-list
  tag: 'latest'

service:
  type: ClusterIP
  ports:
    - name: http
      port: 3000

config:
  configmaps:
    name: black-list